name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    name: HTML & Link Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci --omit=optional --ignore-scripts

      - name: Test and validate site
        run: npm run lint
